flask/statum/main/routes.py
from flask import Blueprint, render_template, request, session, url_for, redirect
from statum.config import Config
from furl import furl
from statum.system.models import System
from statum.users.models import User
from statum.main.utils.utils import generate_token, twitch_login, send_requests, get_vod, get_clips, get_streamer_id, get_data, get_bans, random_indexed_stream, random_stream, add_to_favourites, sort_vod, date_conversion
from statum.main.utils.scheduled import periodic_index_clearance

main = Blueprint('main', __name__)

@main.route("/")
def index():
    if session:
        return redirect(url_for("main.dashboard"))
    return render_template("index.html", login_url=Config.LOGIN_URL)

@main.route("/dashboard")
async def dashboard():
    f: str = furl(request.full_path) 
    streamer_data: dict = {}
    top_streamer_data: dict = {}
    clips_data: dict = {}

    if session:
        streamer_list = session["user"]["follower_list"]
        user_data_id: int = session["user"]["_id"]
        favourites = User.load_favourites(user_data_id)

    if f.args:
        header: dict[str, str] = generate_token()
        twitch_login(header)
        return redirect(url_for("main.dashboard"))
    
    try:
        await send_requests(streamer_data, streamer_list, top_streamer_data, clips_data)
    except UnboundLocalError:
        return redirect(url_for("main.index"))

    return render_template("dashboard.html", live_data=streamer_data, top_data=top_streamer_data, top_clips=clips_data, favourites=favourites, login_url=Config.LOGIN_URL)

@main.route("/vod/<streamer_name>")
async def vod(streamer_name: str):
    header: dict[str, str] = generate_token("bearer")
    vod_data = await get_vod(header, streamer_name)
    vod_length: int = len(vod_data)
    if vod_length > 0:
        return render_template("vod.html", vod_data=vod_data, streamer=streamer_name, vodLength=vod_length)
    else:
        return render_template("vod.html", streamer=streamer_name)

@main.route("/streamer/<streamer_name>")
def streamer(streamer_name: str):
    header: dict[str, str] = generate_token("bearer")
    top_clips: list[list] = get_clips(header, get_streamer_id(header, streamer_name))
    faq_data: dict[str, list] = get_data(streamer_name)
    ban_data: dict = get_bans(streamer_name)
    clip_length: int = len(top_clips)

    return render_template("streamer.html", streamer=streamer_name, top_clips=top_clips, faq_data=faq_data, ban_data=ban_data, clip_length=clip_length)

@main.route("/about")
def about():
    return render_template("about.html", login_url=Config.LOGIN_URL)

@main.route("/privacy")
def privacy():
    return render_template("privacy.html", login_url=Config.LOGIN_URL)
    
@main.route("/tos")
def terms_of_service():
    return render_template("tos.html", login_url=Config.LOGIN_URL)

@main.route("/logout")
def logout():
    user_data_id: int = session["user"]["_id"]
    session.pop("user")
    session.pop("logged_in")
    User.remove_data(user_data_id)
    return redirect(url_for('main.index'))

@main.route("/favourite/<streamer_name>")
def favourite(streamer_name):
    add_to_favourites(streamer_name)
    return redirect(url_for("main.dashboard"))

@main.route("/settings")
def settings():
    user_data_id: int = session["user"]["_id"]
    favourites = User.load_favourites(user_data_id)
    return render_template("settings.html", favourites=favourites, login_url=Config.LOGIN_URL)

@main.route("/favourites")
async def favourites():
    user_data_id: int = session["user"]["_id"]
    header: dict[str, str] = generate_token("bearer")
    favourites = User.load_favourites(user_data_id)
    vod_length: int = 0
    vod_conglomerate: list[list] = []

    for streamer in favourites:
        vod_data = await get_vod(header, streamer, "multiple")  
        vod_length += len(vod_data)
        for n in vod_data:
            vod_conglomerate.append(n)
    
    vod_conglomerate = sort_vod(vod_conglomerate)

    for n in range(len(vod_conglomerate)):
        vod_conglomerate[n][4] = date_conversion(vod_conglomerate[n][4])

    if vod_length > 0:
        return render_template("favourites.html", vod_data=vod_conglomerate, vodLength=vod_length)
    else:
        return render_template("favourites.html")

@main.route("/random")
def randomHTML():
    random_data = System.load_random()

    try:
        if random_data['streamers']:
            user_name = random_indexed_stream(random_data['streamers'])
        else:
            user_name = random_stream()
    except TypeError:
        user_name = random_stream()

    return render_template("random.html", user_name = user_name)

flask/statum/templates/about.html
{% extends "./base/base.html" %}

flask/statum/templates/dashboard.html
{% extends "./base/base.html" %}
{% block streamer %}
    <div class="streamer-area">
        <div class="area-1 area">
            <div class="title-1 title-header gradient-color">
                <h1>followed streamers.</h1>
            </div>
            <div class="data-1">
                {% if session %}
                    {% for streamer in live_data %}
                        <div class="div-streamer">
                            {% if live_data[streamer][0] == "NOT LIVE" %}
                                <h1 class="streamer-box"><a href="{{ url_for('main.streamer', streamer_name = streamer) }}">{{streamer}}</a> is <span class="not-live">{{live_data[streamer][0]}}</span></h1>
                            {% else %}
                                <h1><a href="{{ url_for('main.streamer', streamer_name = streamer) }}">{{streamer}}</a> has been <span class="live">{{live_data[streamer][0]}}</span> for {{ live_data[streamer][2] }} and is currently playing {{ live_data[streamer][1] }}</h1>
                            {% endif %}
                                <div class="clip-area">
                                    <div class="clip-likes icons">
                                        <a href="{{ url_for('main.vod', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/tv.svg') }}" alt=""></a>
                                        <a href="{{ url_for('main.streamer', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/user.svg') }}" alt=""></a>
                                        {% if favourites %}
                                            {% if streamer in favourites %}
                                                <a href="{{ url_for('main.favourite', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/star_fav.svg') }}" alt=""></a>
                                            {% else %}
                                                <a href="{{ url_for('main.favourite', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/star.svg') }}" alt=""></a>
                                            {% endif %}
                                            {% else %}
                                                <a href="{{ url_for('main.favourite', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/star.svg') }}" alt=""></a>
                                        {% endif %}
                                        <a href="https://twitch.tv/{{ streamer }}" target="_blank"><img src="{{ url_for('static', filename='/img/external-link.svg') }}" alt=""></a>
                                    </div>
                                </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="area-2 area">
            <div class="title-2 title-header gradient-color">
                <h1>top streamers.</h1>
            </div>
            <div class="data-2">
                {% if session %}
                    {% for streamer in top_data %}
                        <div class="div-streamer">
                            <h1><a href="{{ url_for('main.streamer', streamer_name = streamer) }}">{{streamer}}</a> has been <span class="live">{{top_data[streamer][0]}}</span> for {{ top_data[streamer][2] }} and is currently playing {{ top_data[streamer][1] }}</h1>
                            <div class="clip-area">
                                <div class="clip-likes icons">
                                    <a href="{{ url_for('main.vod', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/tv.svg') }}" alt=""></a>
                                    <a href="{{ url_for('main.streamer', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/user.svg') }}" alt=""></a>
                                    {% if favourites %}
                                        {% if streamer in favourites %}
                                            <a href="{{ url_for('main.favourite', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/star_fav.svg') }}" alt=""></a>
                                        {% else %}
                                            <a href="{{ url_for('main.favourite', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/star.svg') }}" alt=""></a>
                                        {% endif %}
                                        {% else %}
                                            <a href="{{ url_for('main.favourite', streamer_name = streamer) }}"><img src="{{ url_for('static', filename='/img/star.svg') }}" alt=""></a>
                                    {% endif %}
                                    <a href="https://twitch.tv/{{ streamer }}" target="_blank"><img src="{{ url_for('static', filename='/img/external-link.svg') }}" alt=""></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="area-3 area">
            <div class="title-3 title-header gradient-color">
                <h1>hot clips.</h1>
            </div>
            <div class="data-3">
                {% if session %}
                    {% for clip, url in top_clips.items() %}
                        <div class="div-streamer">
                            <h1><a href="{{ 'reddit.com'.join(['https://', url[0]]) }}" target=”_blank”>{{clip}}</a></h1>
                            <div class="clip-area">
                                <div class="clip-comments">
                                    <img src="{{ url_for('static', filename='/img/message-square.svg') }}" alt="">
                                    <h2>{{ url[2] }}</h2>
                                </div>
                                <div class="clip-likes">
                                    <img src="{{ url_for('static', filename='/img/thumbs-up.svg') }}" alt="">
                                    <h2>{{ url[1] }}</h2>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block dashboard %}
<a class="twitch" href="{{login_url}}">Update Following List</a>
{% endblock %}

flask/statum/templates/favourites.html
{% extends "./base/base.html" %}
{% block top %}
    <div class="vod-top">
        <h1 class="vod-header gradient-color">latest favourite vods.</h1>
    </div>
    <div class="vod-area">
        {% if vod_data %}
            {% for n in range(vodLength) %}
                <a href="{{vod_data[n][1]}}" target="_blank">
                <div class="vod-object">
                    <div class="vod-object-top">
                        <img src="{{vod_data[n][0]}}"/>
                        <span class="views-text">{{vod_data[n][5]}} views</span>
                        <span class="length-text">{{vod_data[n][3]}}</span>
                    </div>
                    <div class="vod-object-bottom">
                        <h3>{{vod_data[n][2]}}</h3>
                        <div class="date-and-username">
                            <h4>{{vod_data[n][4]}}</h4>
                            <h5>{{vod_data[n][6]}}</h5>
                        </div>
                    </div>
                </div>
                </a>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

flask/statum/templates/index.html
{% extends "./base/base.html" %}
{% block header %}
    <div class="header-area">
        <div class="button-area">
            <a class="button-colour button" href="{{login_url}}">Launch Statum</a>
        </div>
    </div>
{% endblock %}
{% block top %}
    <div class="top-area">
        <div class="top-header">
            <h1 class="header-text">STATUM — IN PROGRESS</h1>
            <div class="typed-div">
                <h2 class="header-text">The status platform for <span class="typed"></span></h2>
            </div>
            <h3 class="header-text">Statum allows you to find out in-depth, real-time information about streamers on the Twitch platform.</h3>
        </div>
    </div>
{% endblock %}

flask/statum/templates/privacy.html
{% extends "./base/base.html" %}
{% block top %}
    <div class="tos-area">
        <h1>Privacy Policy for statum</h1>
        <p>At statum, accessible from https://www.statum.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by statum and how we use it.</p>

        <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>

        <p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in statum. This policy is not applicable to any information collected offline or via channels other than this website.</p>

        <h2>Consent</h2>

        <p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>

        <h2>Information we collect</h2>

        <p>The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.</p>
        <p>If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide.</p>
        <p>When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.</p>

        <h2>How we use your information</h2>

        <p>We use the information we collect in various ways, including to:</p>

        <ul>
        <li>Provide, operate, and maintain our website</li>
        <li>Improve, personalize, and expand our website</li>
        <li>Understand and analyze how you use our website</li>
        <li>Develop new products, services, features, and functionality</li>
        <li>Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes</li>
        <li>Send you emails</li>
        <li>Find and prevent fraud</li>
        </ul>

        <h2>Log Files</h2>

        <p>statum follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>

        <h2>Cookies and Web Beacons</h2>

        <p>Like any other website, statum uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>

        <h2>Advertising Partners Privacy Policies</h2>

        <P>You may consult this list to find the Privacy Policy for each of the advertising partners of statum.</p>

        <p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on statum, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>

        <p>Note that statum has no access to or control over these cookies that are used by third-party advertisers.</p>

        <h2>Third Party Privacy Policies</h2>

        <p>statum's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. </p>

        <p>You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>

        <h2>CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>

        <p>Under the CCPA, among other rights, California consumers have the right to:</p>
        <p>Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</p>
        <p>Request that a business delete any personal data about the consumer that a business has collected.</p>
        <p>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</p>
        <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

        <h2>GDPR Data Protection Rights</h2>

        <p>We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</p>
        <p>The right to access – You have the right to request copies of your personal data. We may charge you a small fee for this service.</p>
        <p>The right to rectification – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.</p>
        <p>The right to erasure – You have the right to request that we erase your personal data, under certain conditions.</p>
        <p>The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions.</p>
        <p>The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions.</p>
        <p>The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</p>
        <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

        <h2>Children's Information</h2>

        <p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>

        <p>statum does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>
    </div>
{% endblock %}

flask/statum/templates/random.html
{% extends "./base/base.html" %}
{% block top %}
    <div class="random-area">
        <div class="random-left">
            <iframe src="https://player.twitch.tv/?channel={{ user_name }}&parent=statum-demo.tk" frameborder="0" allowfullscreen="true" scrolling="no" class="iframe-dim"></iframe>
        </div>
        <div class="random-right">
            <h2>You have just started watching <a href="https://twitch.tv/{{ user_name }}" class="gradient-color">{{ user_name }}'s</a> stream.</h2>
            <h3>Supporting smaller content creators is important.</h3>
            <h3>If you enjoy the stream, make sure to drop them a follow!</h3>
            <h3>However, if you wish to skip to find another streamer which suits your needs click the button below.</h3>
            <a href="{{ url_for('main.randomHTML')}}"><img src="{{ url_for('static', filename='/img/arrow-right-circle.svg') }}" alt=""></a>
        </div>
    </div>
{% endblock %}

flask/statum/templates/settings.html
{% extends "./base/base.html" %}
{% block top %}
    <div class="settings-area">
        <div class="setting-1">
            <div class="setting-1-header">
                <h1>List of Favourite Streamers:</h1>
            </div>
            <div class="setting-1-list">
                {% for streamer in favourites %}
                    <h2>{{ streamer }}</h2>
                {% endfor %}
            </div>
        </div>
        <div class="settings-2">
            <div class="setting-forget">
                <a href="{{ url_for('main.logout')}}">Forget Me</a>
            </div>
        </div>
    </div>
{% endblock %}

flask/statum/templates/streamer.html
{% extends "./base/base.html" %}
{% block top %}
    <div class="individual-streamer-area">
        <div class="individual-streamer-area-left">
            <div class="isa-faq-header">
                <h1 class="gradient-color">channel faq.</h1>
            </div>
            <div class="isa-faq">
                <div class="data-point">
                    <h1>{{ streamer }} Twitch stats</h1>
                    {% if faq_data[streamer] %}
                        <h2>In the last 30 days, {{ streamer }} has had a peak of {{ faq_data[streamer][2] }} viewers with an average of {{ faq_data[streamer][1] }} viewers.</h2>
                    {% else %}
                        <h2>Unfortunately, we do not have data for this streamer as this point with regards to their viewership.</h2>
                        {% endif %}
                </div>
                <div class="data-point">
                    <h1>{{ streamer }} rankings on Twitch</h1>
                    {% if faq_data[streamer] %}
                        <h2>Last month {{ streamer }} placed rank {{ faq_data[streamer][0] }} on Twitch based on multiple metrics, including viewership, followers & more.</h2>
                    {% else %}
                        <h2>Unfortunately, we do not have data for this streamer as this point with regards to their Twitch rank.</h2>
                        {% endif %}
                </div>
                <div class="data-point">
                    <h1>{{ streamer }} Twitch views stats</h1>
                    {% if faq_data[streamer] %}
                        <h2>{{ streamer }} currently has {{ faq_data[streamer][5] }} Total Views on Twitch.</h2>
                    {% else %}
                        <h2>Unfortunately, we do not have data for this streamer as this point with regards to their total views.</h2>
                        {% endif %}
                </div>
                <div class="data-point">
                    <h1>{{ streamer }} Twitch follower count</h1>
                    {% if faq_data[streamer] %}
                        <h2>{{ streamer }} currently has {{ faq_data[streamer][4] }} Followers on Twitch, with {{ faq_data[streamer][3] }} followers gained in the last 30 days!</h2>
                    {% else %}
                        <h2>Unfortunately, we do not have data for this streamer as this point with regards to their total follower count.</h2>
                    {% endif %}
                </div>
                <div class="data-point">
                    <h1>How much does {{ streamer }} make on Twitch?</h1>
                    <h2><a href="https://twitch.pages.dev/earnings/{{ streamer.lower() }}" target="_blank">👀</a></h2>
                </div>
            </div>
        </div>
        <div class="individual-streamer-area-middle">
            <div class="isa-bans-header">
                <h1 class="gradient-color">current ban status.</h1>
            </div>
            <div class="isa-bans">
                <div class="data-point">
                    {% if ban_data[streamer][1] == 0 %}
                        <h1>{{ streamer }} is <span class="live">NOT</span> currently banned.</h1>
                    {% else %}
                        <h1>{{ streamer }} <span class="not-live">IS</span> currently banned.</h1>
                    {% endif %}
                </div>
                <div class="data-point">
                    <h1>How many times has {{ streamer }} been banned?</h1>
                    {% if ban_data[streamer][0][0] %}
                        <h2>{{ streamer }} has been banned {{ ban_data[streamer][0][0] }} time(s).</h2>
                    {% else %}
                        <h2>{{ streamer }} has never been banned.</h2>
                    {% endif %}
                </div>
                <div class="data-point">
                    <h1>When was {{ streamer }}'s last ban?</h1>
                    {% if ban_data[streamer][0][1] %}
                        <h2>{{ streamer }}'s last ban was {{ ban_data[streamer][0][1] }}.</h2>
                    {% else %}
                        <h2>{{ streamer }} has never had a last ban, yet.</h2>
                        {% endif %}
                </div>
                <div class="data-point">
                    <h1>What was {{ streamer }}'s longest ban?</h1>
                    {% if ban_data[streamer][0][2] %}
                        <h2>{{ streamer }}'s longest ban was {{ ban_data[streamer][0][2] }}.</h2>
                    {% else %}
                        <h2>{{ streamer }}'s longest ban was approximately 0 seconds long.</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    <div class="individual-streamer-area-right">
        <div class="isa-clips-header">
            <h1 class="gradient-color">top clips.</h1>
        </div>
        <div class="clip-area">
            {% if top_clips %}
                {% for n in range(clip_length) %}
                    <a href="{{top_clips[n][4]}}" target="_blank">
                    <div class="clip-object">
                        <div class="vod-object-top">
                            <img src="{{top_clips[n][5]}}"/>
                            <span class="views-text">{{top_clips[n][0]}} views</span>
                            <span class="length-text">{{top_clips[n][1]}} s</span>
                        </div>
                        <div class="vod-object-bottom">
                            <h3>{{top_clips[n][2]}}</h3>
                            <h4>{{top_clips[n][3]}}</h4>
                        </div>
                    </div>
                    </a>
                {% endfor %}
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

flask/statum/templates/vod.html
{% extends "./base/base.html" %}
{% block top %}
    <div class="vod-top">
        <h1 class="vod-header gradient-color">latest {{streamer}} vods.</h1>
    </div>
    <div class="vod-area">
        {% if vod_data %}
            {% for n in range(vodLength) %}
                <a href="{{vod_data[n][1]}}" target="_blank">
                <div class="vod-object">
                    <div class="vod-object-top">
                        <img src="{{vod_data[n][0]}}"/>
                        <span class="views-text">{{vod_data[n][5]}} views</span>
                        <span class="length-text">{{vod_data[n][3]}}</span>
                    </div>
                    <div class="vod-object-bottom">
                        <h3>{{vod_data[n][2]}}</h3>
                        <h4>{{vod_data[n][4]}}</h4>
                    </div>
                </div>
                </a>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}